#!/usr/bin/env python3
"""
kalibr_to_vins.py
=================

Convert a Kalibr calibration result (camera intrinsics + extrinsics + IMU)
into a complete VINS-Fisheye configuration set:

    <out_dir>/cam0_mei.yaml
    <out_dir>/cam1_mei.yaml          (one per camera in the chain)
    <out_dir>/stereo_imu_config.yaml (main config; uses the chosen pair)
    <launch_dir>/<launch_name>.launch (optional)

Inputs expected in --kalibr-dir (Kalibr default file names):
    *camchain-imucam*.yaml   (gives T_cam_imu for the reference camera)
    *camchain*.yaml          (intrinsics + chain of T_cn_cnm1)
    *imu*.yaml               (IMU noise/random-walk + update_rate)

Camera model assumption
-----------------------
Supported Kalibr camera models are ``eucm-none``, ``omni-radtan``,
``pinhole-radtan`` and ``pinhole-equi``. They are emitted as EUCM, MEI,
PINHOLE and KANNALA_BRANDT respectively.

Usage
-----
    python3 scripts/kalibr_to_vins.py \
        --kalibr-dir my_kalibr_result \
        --out-dir   config/my_kalibr_fisheye \
        --cam-pair  0,1 \
        --topic-map 0:/fisheye/left/image_raw,1:/fisheye/right/image_raw,\\
2:/fisheye/bleft/image_raw,3:/fisheye/bright/image_raw \
        --imu-topic /imu_data_raw \
        --compressed \
        --launch    my_kalibr_fisheye

Re-run the script whenever the Kalibr result changes; it is idempotent.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
import yaml


# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

def find_one(pattern: str, root: Path) -> Path:
    matches = sorted(root.glob(pattern))
    if not matches:
        raise FileNotFoundError(f"No file matching {pattern!r} under {root}")
    if len(matches) > 1:
        print(f"[warn] multiple matches for {pattern!r}: {matches}, using {matches[0]}")
    return matches[0]


def load_yaml(path: Path) -> dict:
    with path.open() as f:
        return yaml.safe_load(f)


def invert_se3(T: np.ndarray) -> np.ndarray:
    R, t = T[:3, :3], T[:3, 3]
    Ti = np.eye(4)
    Ti[:3, :3] = R.T
    Ti[:3, 3] = -R.T @ t
    return Ti


def num_cameras(camchain: dict) -> int:
    n = 0
    while f"cam{n}" in camchain:
        n += 1
    return n


def T_imu_cam(camchain: dict, T_imu_cam0: np.ndarray, n: int) -> np.ndarray:
    """body_T_camN = T_imu_cam0 * inv(T_camN_cam0).
    T_camN_cam0 = T_cn_cnm1[N] @ ... @ T_cn_cnm1[1]."""
    if n == 0:
        return T_imu_cam0
    T_camN_cam0 = np.eye(4)
    for i in range(1, n + 1):
        T_ci_cim1 = np.array(camchain[f"cam{i}"]["T_cn_cnm1"])
        T_camN_cam0 = T_ci_cim1 @ T_camN_cam0
    return T_imu_cam0 @ invert_se3(T_camN_cam0)


def fmt_matrix(M: np.ndarray, indent: str = "           ") -> str:
    rows = []
    for r in M:
        rows.append(indent + ", ".join(f"{v: .16e}" for v in r))
    return ",\n".join(rows)


# -----------------------------------------------------------------------------
# Camera-yaml emitters (one model per camera)
# -----------------------------------------------------------------------------

def emit_camera_yaml(out_path: Path, cam_idx: int, cam: dict,
                     pad_top: int = 0, pad_bottom: int = 0,
                     pad_left: int = 0, pad_right: int = 0) -> str:
    """Write a VINS camera-intrinsics yaml. Returns the file basename.

    Padding shifts the principal point (u0, v0) accordingly and grows the
    declared image size, so the kalibr-fitted intrinsics remain valid for
    the padded image (the lens-sensor relationship doesn't change; we just
    place the active region inside a larger canvas)."""
    model_kalibr = f"{cam.get('camera_model','omni')}-{cam.get('distortion_model','radtan')}"
    intr = cam["intrinsics"]
    dist = cam["distortion_coeffs"]
    w, h = cam["resolution"]
    name = f"cam{cam_idx}"

    # Padded geometry
    w_pad = int(w) + pad_left + pad_right
    h_pad = int(h) + pad_top + pad_bottom

    if model_kalibr == "eucm-none":
        alpha, beta, fx, fy, cx, cy = intr
        cx_pad = cx + pad_left
        cy_pad = cy + pad_top
        body = f"""%YAML:1.0
---
# Generated by kalibr_to_vins.py from camchain.yaml ({name})
# Kalibr EUCM parameters are preserved exactly.
# Pad applied (top,bottom,left,right) = ({pad_top},{pad_bottom},{pad_left},{pad_right})
model_type: EUCM
camera_name: {name}
image_width: {w_pad}
image_height: {h_pad}
projection_parameters:
   alpha: {alpha:.16e}
   beta: {beta:.16e}
   fx: {fx:.16e}
   fy: {fy:.16e}
   cx: {cx_pad:.16e}
   cy: {cy_pad:.16e}
"""
    elif model_kalibr == "omni-radtan":
        xi, fx, fy, cx, cy = intr
        k1, k2, p1, p2 = dist
        cx_pad = cx + pad_left
        cy_pad = cy + pad_top
        body = f"""%YAML:1.0
---
# Generated by kalibr_to_vins.py from camchain.yaml ({name})
# Kalibr "omni-radtan" -> VINS "MEI"
# Pad applied (top,bottom,left,right) = ({pad_top},{pad_bottom},{pad_left},{pad_right})
model_type: MEI
camera_name: {name}
image_width: {w_pad}
image_height: {h_pad}
mirror_parameters:
   xi: {xi:.16e}
distortion_parameters:
   k1: {k1:.16e}
   k2: {k2:.16e}
   p1: {p1:.16e}
   p2: {p2:.16e}
projection_parameters:
   gamma1: {fx:.16e}
   gamma2: {fy:.16e}
   u0: {cx_pad:.16e}
   v0: {cy_pad:.16e}
"""
    elif model_kalibr == "pinhole-radtan":
        fx, fy, cx, cy = intr
        k1, k2, p1, p2 = dist
        cx_pad = cx + pad_left
        cy_pad = cy + pad_top
        body = f"""%YAML:1.0
---
# Generated by kalibr_to_vins.py from camchain.yaml ({name})
# Kalibr "pinhole-radtan" -> VINS "PINHOLE"
# Pad applied (top,bottom,left,right) = ({pad_top},{pad_bottom},{pad_left},{pad_right})
model_type: PINHOLE
camera_name: {name}
image_width: {w_pad}
image_height: {h_pad}
distortion_parameters:
   k1: {k1:.16e}
   k2: {k2:.16e}
   p1: {p1:.16e}
   p2: {p2:.16e}
projection_parameters:
   fx: {fx:.16e}
   fy: {fy:.16e}
   cx: {cx_pad:.16e}
   cy: {cy_pad:.16e}
"""
    elif model_kalibr == "pinhole-equi":
        fx, fy, cx, cy = intr
        k1, k2, k3, k4 = dist
        cx_pad = cx + pad_left
        cy_pad = cy + pad_top
        body = f"""%YAML:1.0
---
# Generated by kalibr_to_vins.py from camchain.yaml ({name})
# Kalibr "pinhole-equi" -> VINS "KANNALA_BRANDT"
# Pad applied (top,bottom,left,right) = ({pad_top},{pad_bottom},{pad_left},{pad_right})
model_type: KANNALA_BRANDT
camera_name: {name}
image_width: {w_pad}
image_height: {h_pad}
projection_parameters:
   k2: {k1:.16e}
   k3: {k2:.16e}
   k4: {k3:.16e}
   k5: {k4:.16e}
   mu: {fx:.16e}
   mv: {fy:.16e}
   u0: {cx_pad:.16e}
   v0: {cy_pad:.16e}
"""
    else:
        raise ValueError(
            f"Unsupported Kalibr model {model_kalibr!r} for {name}. "
            "Supported: eucm-none, omni-radtan, pinhole-radtan, pinhole-equi."
        )

    fname = f"{name}_{ {'eucm-none':'eucm','omni-radtan':'mei','pinhole-radtan':'pinhole','pinhole-equi':'kb'}[model_kalibr] }.yaml"
    (out_path / fname).write_text(body)
    return fname


# -----------------------------------------------------------------------------
# Main config emitter
# -----------------------------------------------------------------------------

def emit_main_config(
    out_path: Path,
    cam_pair: Tuple[int, int],
    cam_files: Dict[int, str],
    Tic: Dict[int, np.ndarray],
    resolution: Tuple[int, int],
    imu: dict,
    topic_map: Dict[int, str],
    imu_topic: str,
    compressed: bool,
    use_gpu: int,
    imu_noise_scale: float,
    output_path: str,
    timeshift_cam_imu: float,
    estimate_td: int,
    is_fisheye: int = 1,
    fisheye_fov: float = 200.0,
    enable_sides: int = 0,
    show_track: int = -1,
    pad_top: int = 0,
    pad_bottom: int = 0,
    pad_left: int = 0,
    pad_right: int = 0,
    padded_topic_suffix: str = "/image_padded",
    flatten_width: int = 600,
    flatten_height: int = 200,
    show_width: int = 1080,
) -> Path:
    a, b = cam_pair
    w, h = resolution
    body_T_cam0 = Tic[a]
    body_T_cam1 = Tic[b]

    # Padded image dimensions (advertised to VINS; raw fisheye_fov sub-image
    # sampler then sees a "square-ish" canvas matching its symmetry assumption).
    w_pad = int(w) + pad_left + pad_right
    h_pad = int(h) + pad_top + pad_bottom
    padding_active = (pad_top + pad_bottom + pad_left + pad_right) > 0

    raw0, raw1 = topic_map[a], topic_map[b]
    # Strip "/compressed" if user passed compressed topics directly
    if raw0.endswith("/compressed"):
        raw0 = raw0[: -len("/compressed")]
    if raw1.endswith("/compressed"):
        raw1 = raw1[: -len("/compressed")]
    comp0 = raw0 + "/compressed"
    comp1 = raw1 + "/compressed"

    if padding_active:
        # Padder consumes raw or compressed input, publishes to a new raw topic
        # that ends in `padded_topic_suffix`. VINS subscribes to that.
        # Strip the trailing /image_raw (or whatever) suffix and replace.
        def _padded(t: str) -> str:
            base = t.rsplit("/", 1)[0] if "/" in t else t
            return base + padded_topic_suffix
        raw0_in_for_vins = _padded(raw0)
        raw1_in_for_vins = _padded(raw1)
        comp0_in_for_vins = raw0_in_for_vins + "/compressed"
        comp1_in_for_vins = raw1_in_for_vins + "/compressed"
        # When padder is active, padded output is RAW, so force compressed-mode off
        compressed_for_vins = False
    else:
        raw0_in_for_vins = raw0
        raw1_in_for_vins = raw1
        comp0_in_for_vins = comp0
        comp1_in_for_vins = comp1
        compressed_for_vins = compressed

    acc_n = imu["accelerometer_noise_density"] * imu_noise_scale
    gyr_n = imu["gyroscope_noise_density"] * imu_noise_scale
    acc_w = imu["accelerometer_random_walk"] * imu_noise_scale
    gyr_w = imu["gyroscope_random_walk"] * imu_noise_scale
    update_rate = int(imu.get("update_rate", 200))

    # Auto-coordinate show_track with enable_sides:
    # drawTrackFisheye() in feature_tracker_fisheye.hpp:319 unconditionally
    # divides by imUpSide.size().width, which is 0 when sides are disabled,
    # causing a cv::resize assertion failure. So when sides are off we must
    # also force show_track=0. The user can override via --show-track.
    if show_track < 0:
        show_track = 1 if enable_sides else 0
    elif show_track == 1 and not enable_sides:
        print("[warn] show_track=1 without enable_sides=1 will crash "
              "drawTrackFisheye(). Forcing show_track=0.")
        show_track = 0

    cfg = f"""%YAML:1.0

#==========================================================
# Auto-generated by kalibr_to_vins.py — DO NOT EDIT BY HAND.
# Re-run the script to refresh.
#
# Camera pair selected: cam{a} + cam{b}
# IMU topic           : {imu_topic}
# Configured inputs   : {raw0} / {raw1}
# VINS subscribes to  : {raw0_in_for_vins} / {raw1_in_for_vins}
# Compressed input    : {bool(compressed_for_vins)}
# Padding             : top={pad_top} bottom={pad_bottom} left={pad_left} right={pad_right}
#                       (pad_fisheye_node.py rebuilds the symmetric fisheye)
# is_fisheye          : {int(is_fisheye)}  (1 = dual-fisheye spherical mode;
#                       this fork only implements the is_fisheye:1 path —
#                       the is_fisheye:0 branch in estimator.cpp is empty
#                       and segfaults at runtime.)
#==========================================================

#common parameters
imu: 1
num_of_cam: 2

is_fisheye: {int(is_fisheye)}

imu_topic: "{imu_topic}"

# Raw image topics (used when is_compressed_images:0)
image0_topic: "{raw0_in_for_vins}"
image1_topic: "{raw1_in_for_vins}"

# Compressed image topics (used when is_compressed_images:1)
is_compressed_images: {1 if compressed_for_vins else 0}
compressed_image0_topic: "{comp0_in_for_vins}"
compressed_image1_topic: "{comp1_in_for_vins}"

output_path: "{output_path}"

cam0_calib: "{cam_files[a]}"
cam1_calib: "{cam_files[b]}"

# image_width/height here are the FLATTENED virtual-pinhole sub-image
# dimensions (used as WIDTH inside FisheyeUndist), NOT the input fisheye
# resolution. Recommended 300-600 for VIO. The actual padded input size
# ({w_pad} x {h_pad}) is declared inside cam{a}_*.yaml / cam{b}_*.yaml.
image_width: {int(flatten_width)}
image_height: {int(flatten_height)}
show_width: {int(show_width)}      # SHOW_WIDTH for the show_track visualization

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  trust the matrices below; 1  refine online.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [
{fmt_matrix(body_T_cam0)} ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [
{fmt_matrix(body_T_cam1)} ]

#Multiple thread support
multiple_thread: 1
#GPU acceleration
use_gpu: {int(use_gpu)}
use_vxworks: 0

# Dual-fisheye sub-image flags. Each fisheye camera is unwarped into
# 5 virtual pinhole sub-images (top + 4 sides). For forward-facing stereo
# the "top" sub-image (cam optical axis) is the most useful one.
fisheye_fov: {float(fisheye_fov)}
enable_up_top: 1
enable_down_top: 1
enable_up_side: {int(enable_sides)}
enable_down_side: {int(enable_sides)}
enable_rear_side: 0
thres_outlier: 5.0
tri_max_err: 3.0
pub_flatten: 0
pub_flatten_freq: 10
flatten_color: 0
enable_downsample: 0

enable_depth: 0
rgb_depth_cloud: -1
depth_estimate_baseline: 0.05
depth_config: "depth_cpu.yaml"
top_cnt: 150
side_cnt: 100

#feature tracker parameters
max_cnt: 150
max_solve_cnt: 150
min_dist: 30
freq: 10
F_threshold: 1.0
show_track: {int(show_track)}
flow_back: 1
enable_perf_output: 0
use_orb: 0

warn_imu_freq: 0
warn_imu_duration: 0
imu_freq: {update_rate}
image_freq: 30

#optimization parameters
max_solver_time: 0.04
max_num_iterations: 8
keyframe_parallax: 10.0

#imu parameters (kalibr-derived, scaled by --imu-noise-scale = {imu_noise_scale})
acc_n: {acc_n:.8g}
gyr_n: {gyr_n:.8g}
acc_w: {acc_w:.8g}
gyr_w: {gyr_w:.8g}
g_norm: 9.81

#unsynchronization parameters
estimate_td: {int(estimate_td)}
td: {timeshift_cam_imu:.16e}      # kalibr "timeshift_cam_imu"

#loop closure parameters
load_previous_pose_graph: 0
pose_graph_save_path: "{output_path}/pose_graph/"
save_image: 0

#rectify
publish_rectify: 0
cam0_rectify: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1, 0, 0,
           0, 1, 0,
           0, 0, 1 ]
cam1_rectify: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1, 0, 0,
           0, 1, 0,
           0, 0, 1 ]
"""
    target = out_path / "stereo_imu_config.yaml"
    target.write_text(cfg)
    return target


# -----------------------------------------------------------------------------
# Optional launch-file emitter
# -----------------------------------------------------------------------------

def emit_launch(launch_dir: Path, launch_name: str, config_path: Path,
                padder_specs: "list | None" = None,
                viz_spec: "dict | None" = None) -> Path:
    """Emit a roslaunch file. If padder_specs is non-empty, prepend
    pad_fisheye_node.py instances. Each spec is a dict with keys:
        input, output, input_compressed, pad_top, pad_bottom, pad_left, pad_right

    If viz_spec is given, also append a viz_fisheye_tracking.py node. Keys:
        left_topic, right_topic, left_compressed, right_compressed, display
    """
    rel = os.path.relpath(config_path, launch_dir.parent / "..")
    repo_root = (launch_dir.parent / "..").resolve()
    scripts_rel = "../scripts/pad_fisheye_node.py"

    def _pkg_rel(abs_path: str) -> str:
        """Convert an absolute path under repo_root to '$(find vins)/../<rel>'.
        Leave it untouched if it's empty or lives outside the package.
        Without this, an absolute host path baked into the launch file fails
        when ROS runs inside a container that mounts the repo at a different
        absolute path."""
        if not abs_path:
            return abs_path
        try:
            p = Path(abs_path).resolve()
            rel_p = p.relative_to(repo_root)
            return f"$(find vins)/../{rel_p}"
        except (ValueError, OSError):
            return abs_path
    padder_xml = ""
    if padder_specs:
        for i, p in enumerate(padder_specs):
            padder_xml += f"""
    <!-- Padder for cam{i}: rebuilds symmetric fisheye geometry -->
    <node pkg="vins" type="pad_fisheye_node.py" name="fisheye_padder_{i}"
          output="screen" required="true">
        <param name="input"            type="string" value="{p['input']}"/>
        <param name="output"           type="string" value="{p['output']}"/>
        <param name="input_compressed" type="bool"   value="{str(bool(p['input_compressed'])).lower()}"/>
        <param name="pad_top"          type="int"    value="{int(p['pad_top'])}"/>
        <param name="pad_bottom"       type="int"    value="{int(p['pad_bottom'])}"/>
        <param name="pad_left"         type="int"    value="{int(p['pad_left'])}"/>
        <param name="pad_right"        type="int"    value="{int(p['pad_right'])}"/>
    </node>
"""
        padder_xml += "\n    <!-- Wait briefly so VINS sees the padded topic available -->\n"

    viz_xml = ""
    if viz_spec:
        viz_xml = f"""
    <!-- Stereo fisheye tracking + VINS trajectory visualizer -->
    <node pkg="vins" type="viz_fisheye_tracking.py" name="viz_fisheye_tracking"
          output="screen">
        <param name="left_topic"       type="string" value="{viz_spec['left_topic']}"/>
        <param name="right_topic"      type="string" value="{viz_spec['right_topic']}"/>
        <param name="left_compressed"  type="bool"   value="{str(bool(viz_spec['left_compressed'])).lower()}"/>
        <param name="right_compressed" type="bool"   value="{str(bool(viz_spec['right_compressed'])).lower()}"/>
        <param name="display"          type="bool"   value="{str(bool(viz_spec.get('display', True))).lower()}"/>
        <param name="show_width"       type="int"    value="{int(viz_spec.get('show_width', 1600))}"/>
        <param name="traj_height"      type="int"    value="{int(viz_spec.get('traj_height', 360))}"/>
        <param name="header_height"    type="int"    value="{int(viz_spec.get('header_height', 44))}"/>
        <param name="max_corners"      type="int"    value="{int(viz_spec.get('max_corners', 200))}"/>
        <param name="min_distance"     type="int"    value="{int(viz_spec.get('min_distance', 25))}"/>
        <param name="trail_length"     type="int"    value="{int(viz_spec.get('trail_length', 12))}"/>
        <param name="output_topic"     type="string" value="{viz_spec.get('output_topic', '/vins/fisheye_track')}"/>
        <param name="path_topic"       type="string" value="{viz_spec.get('path_topic', '/vins_estimator/path')}"/>
        <param name="odom_topic"       type="string" value="{viz_spec.get('odom_topic', '/vins_estimator/odometry')}"/>
        <param name="mask_path"        type="string" value="{_pkg_rel(viz_spec.get('mask_path', ''))}"/>
    </node>
"""

    body = f"""<launch>
    <!--
        Auto-generated by kalibr_to_vins.py.
        Run:
            roslaunch vins {launch_name}.launch
            rosbag play YOUR.bag (use the clock flag)

        NOTE on the pad_fisheye_node.py path: roslaunch finds it via
            rosrun vins pad_fisheye_node.py
        which requires CMakeLists.txt to install scripts/, OR the script
        being on PATH. We use rosrun-style lookup; if not found, copy or
        symlink scripts/pad_fisheye_node.py into the package install dir,
        or just run it directly:
            python3 {scripts_rel} _input:=... _output:=...
    -->
    <arg name="config_file" default="$(find vins)/../{rel}" />
    <arg name="viz"         default="true" />
{padder_xml}{viz_xml}
    <node pkg="vins" type="vins_node_fisheye" name="vins_estimator" output="screen">
        <param name="config_file" type="string" value="$(arg config_file)"/>
        <param name="fisheye_external_flatten" type="bool" value="false"/>
    </node>

    <include file="$(find vins)/launch/vins_rviz.launch" if="$(arg viz)" />
</launch>
"""
    target = launch_dir / f"{launch_name}.launch"
    target.write_text(body)
    return target


# -----------------------------------------------------------------------------
# Argument parsing
# -----------------------------------------------------------------------------

def parse_topic_map(s: str, ncam: int) -> Dict[int, str]:
    if not s:
        return {i: f"/cam{i}/image_raw" for i in range(ncam)}
    out: Dict[int, str] = {}
    for piece in s.split(","):
        piece = piece.strip()
        if not piece:
            continue
        idx, topic = piece.split(":", 1)
        out[int(idx)] = topic.strip()
    for i in range(ncam):
        out.setdefault(i, f"/cam{i}/image_raw")
    return out


def parse_pair(s: str) -> Tuple[int, int]:
    a, b = (int(x) for x in s.split(","))
    return a, b


def main(argv=None):
    here = Path(__file__).resolve().parent
    repo_root = here.parent  # .../VINS-Fisheye

    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--kalibr-dir", type=Path,
                   default=repo_root / "my_kalibr_result",
                   help="Directory containing kalibr *.yaml outputs.")
    p.add_argument("--out-dir", type=Path,
                   default=repo_root / "config" / "my_kalibr_fisheye",
                   help="Destination directory for VINS yaml files.")
    p.add_argument("--cam-pair", default="0,1",
                   help="Indices of the stereo pair, e.g. 0,1 or 2,3.")
    p.add_argument("--topic-map", default="0:/fisheye/left/image_raw,"
                                          "1:/fisheye/right/image_raw,"
                                          "2:/fisheye/bleft/image_raw,"
                                          "3:/fisheye/bright/image_raw",
                   help="Comma-separated cam_idx:topic pairs (raw image topic).")
    p.add_argument("--imu-topic", default="/imu_data_raw",
                   help="ROS topic for sensor_msgs/Imu in the bag.")
    p.add_argument("--compressed", action="store_true", default=True,
                   help="Set is_compressed_images:1 in the main config (default ON).")
    p.add_argument("--no-compressed", dest="compressed", action="store_false",
                   help="Disable compressed image input.")
    p.add_argument("--use-gpu", type=int, default=0, choices=[0, 1],
                   help="use_gpu flag (set 1 only if you built with CUDA support).")
    p.add_argument("--imu-noise-scale", type=float, default=10.0,
                   help="Multiplier applied to kalibr IMU noise/random-walk (default 10x).")
    p.add_argument("--output-path", default="/home/lhk/output",
                   help="VINS output_path field.")
    p.add_argument("--estimate-td", type=int, default=0, choices=[0, 1],
                   help="Estimate camera/IMU time offset online. Default 0 uses "
                        "Kalibr's timeshift_cam_imu as a fixed value.")
    p.add_argument("--is-fisheye", type=int, default=1, choices=[0, 1],
                   help="is_fisheye flag. NOTE: this fork only implements the "
                        "is_fisheye:1 dual-fisheye path; is_fisheye:0 segfaults.")
    p.add_argument("--fisheye-fov", type=float, default=200.0,
                   help="Total fisheye FOV in degrees (used for sub-image sampling).")
    p.add_argument("--enable-sides", type=int, default=0, choices=[0, 1],
                   help="Enable the 4 side sub-images per camera (default off; "
                        "for forward-facing stereo, side sub-images often have "
                        "no useful content).")
    p.add_argument("--show-track", type=int, default=-1, choices=[-1, 0, 1],
                   help="show_track flag. -1 (default) = auto: 1 if sides "
                        "enabled, 0 otherwise. drawTrackFisheye() crashes when "
                        "sides are disabled, so this auto-mode prevents that.")
    p.add_argument("--pad-top",    type=int, default=0,
                   help="Pad N pixels of black on top of each image at runtime.")
    p.add_argument("--pad-bottom", type=int, default=0,
                   help="Pad N pixels of black on bottom of each image at runtime.")
    p.add_argument("--pad-left",   type=int, default=0,
                   help="Pad N pixels of black on left of each image at runtime.")
    p.add_argument("--pad-right",  type=int, default=0,
                   help="Pad N pixels of black on right of each image at runtime.")
    p.add_argument("--padded-suffix", default="/image_padded",
                   help="Topic suffix appended to the basename for padded output "
                        "(e.g. /fisheye/left -> /fisheye/left/image_padded).")
    p.add_argument("--flatten-width",  type=int, default=600,
                   help="Width of the virtual-pinhole sub-images produced by "
                        "FisheyeUndist (main yaml's image_width). Recommended "
                        "300-600 for VIO. Lower = faster.")
    p.add_argument("--flatten-height", type=int, default=200,
                   help="Height of the side virtual-pinhole strip "
                        "(main yaml's image_height).")
    p.add_argument("--show-width",     type=int, default=1080,
                   help="show_width: width of the show_track visualization "
                        "window. Must be > 0 or drawTrackFisheye crashes.")
    p.add_argument("--external-viz", type=int, default=1, choices=[0, 1],
                   help="Add a viz_fisheye_tracking.py node to the launch file "
                        "(simple side-by-side fisheye tracking window, "
                        "independent of VINS's internal show_track). When 1, "
                        "VINS's own show_track is also auto-disabled.")
    p.add_argument("--fisheye-mask", default="",
                   help="Path to a fisheye PNG mask (white = valid, black = "
                        "ignore). The viz node will only detect features "
                        "inside the mask. Auto-padded if its aspect ratio "
                        "differs from the runtime image (e.g. mask drawn for "
                        "the un-padded sensor).")
    p.add_argument("--launch", default=None,
                   help="If set, write vins_estimator/launch/<NAME>.launch alongside.")
    p.add_argument("--launch-dir", type=Path,
                   default=repo_root / "vins_estimator" / "launch",
                   help="Directory for the optional launch file.")
    args = p.parse_args(argv)

    # ------- locate kalibr files -------
    kalibr_dir = args.kalibr_dir.resolve()
    if not kalibr_dir.exists():
        sys.exit(f"[err] kalibr dir does not exist: {kalibr_dir}")
    imucam_path   = find_one("*camchain-imucam*.yaml", kalibr_dir)
    camchain_path = find_one("*camchain.yaml",         kalibr_dir)
    imu_path      = find_one("*imu-imu*.yaml",         kalibr_dir)

    print(f"[info] imucam   : {imucam_path}")
    print(f"[info] camchain : {camchain_path}")
    print(f"[info] imu      : {imu_path}")

    imucam   = load_yaml(imucam_path)
    camchain = load_yaml(camchain_path)
    imu_yaml = load_yaml(imu_path)

    ncam = num_cameras(camchain)
    if ncam == 0:
        sys.exit("[err] no cameras found in camchain")
    print(f"[info] detected {ncam} cameras (cam0..cam{ncam-1})")

    # ------- compute extrinsics -------
    T_cam0_imu = np.array(imucam["cam0"]["T_cam_imu"])
    T_imu_cam0 = invert_se3(T_cam0_imu)
    Tic = {i: T_imu_cam(camchain, T_imu_cam0, i) for i in range(ncam)}
    timeshift = float(imucam["cam0"].get("timeshift_cam_imu", 0.0))

    # ------- write output -------
    args.out_dir.mkdir(parents=True, exist_ok=True)
    cam_files: Dict[int, str] = {}
    resolution = tuple(camchain["cam0"]["resolution"])
    for i in range(ncam):
        cam_files[i] = emit_camera_yaml(
            args.out_dir, i, camchain[f"cam{i}"],
            pad_top=args.pad_top, pad_bottom=args.pad_bottom,
            pad_left=args.pad_left, pad_right=args.pad_right,
        )
        print(f"[ok ] wrote {args.out_dir/cam_files[i]}")

    cam_pair = parse_pair(args.cam_pair)
    if cam_pair[0] not in Tic or cam_pair[1] not in Tic:
        sys.exit(f"[err] cam-pair {cam_pair} out of range (have 0..{ncam-1})")
    topic_map = parse_topic_map(args.topic_map, ncam)

    # When the external viz node is on, force VINS's broken show_track off.
    show_track_arg = args.show_track
    if args.external_viz and show_track_arg != 0:
        print("[info] --external-viz=1 -> forcing VINS show_track:0 "
              "(use the standalone viz_fisheye_tracking window instead)")
        show_track_arg = 0

    imu0 = imu_yaml["imu0"]
    main_yaml = emit_main_config(
        out_path=args.out_dir,
        cam_pair=cam_pair,
        cam_files=cam_files,
        Tic=Tic,
        resolution=resolution,
        imu=imu0,
        topic_map=topic_map,
        imu_topic=args.imu_topic,
        compressed=args.compressed,
        use_gpu=args.use_gpu,
        imu_noise_scale=args.imu_noise_scale,
        output_path=args.output_path,
        timeshift_cam_imu=timeshift,
        estimate_td=args.estimate_td,
        is_fisheye=args.is_fisheye,
        fisheye_fov=args.fisheye_fov,
        enable_sides=args.enable_sides,
        show_track=show_track_arg,
        pad_top=args.pad_top, pad_bottom=args.pad_bottom,
        pad_left=args.pad_left, pad_right=args.pad_right,
        padded_topic_suffix=args.padded_suffix,
        flatten_width=args.flatten_width,
        flatten_height=args.flatten_height,
        show_width=args.show_width,
    )
    print(f"[ok ] wrote {main_yaml}")

    # ------- build padder specs (only if any padding requested) -------
    padder_specs = []
    pad_total = args.pad_top + args.pad_bottom + args.pad_left + args.pad_right
    if pad_total > 0:
        for cam_idx in cam_pair:
            src = topic_map[cam_idx]
            if src.endswith("/compressed"):
                src = src[: -len("/compressed")]
            base = src.rsplit("/", 1)[0] if "/" in src else src
            padded_out = base + args.padded_suffix
            padder_specs.append({
                "input": (src + "/compressed") if args.compressed else src,
                "output": padded_out,
                "input_compressed": args.compressed,
                "pad_top": args.pad_top,
                "pad_bottom": args.pad_bottom,
                "pad_left": args.pad_left,
                "pad_right": args.pad_right,
            })

    # ------- build viz spec (so the launch file knows what topics to viz) -------
    viz_spec = None
    if args.external_viz:
        # Subscribe to whichever topic actually carries the images we want VINS
        # to consume. With padding active, that's the padded raw topic; without
        # padding, the original raw or compressed topic the user supplied.
        a, b = cam_pair
        raw_a = topic_map[a]
        raw_b = topic_map[b]
        if raw_a.endswith("/compressed"):
            raw_a = raw_a[: -len("/compressed")]
        if raw_b.endswith("/compressed"):
            raw_b = raw_b[: -len("/compressed")]
        if pad_total > 0:
            base_a = raw_a.rsplit("/", 1)[0] if "/" in raw_a else raw_a
            base_b = raw_b.rsplit("/", 1)[0] if "/" in raw_b else raw_b
            viz_left  = base_a + args.padded_suffix
            viz_right = base_b + args.padded_suffix
            viz_left_comp = False
            viz_right_comp = False
        else:
            viz_left  = raw_a + ("/compressed" if args.compressed else "")
            viz_right = raw_b + ("/compressed" if args.compressed else "")
            viz_left_comp = bool(args.compressed)
            viz_right_comp = bool(args.compressed)
        viz_spec = {
            "left_topic":  viz_left,
            "right_topic": viz_right,
            "left_compressed":  viz_left_comp,
            "right_compressed": viz_right_comp,
            "display": True,
            "show_width": 1600,
            "max_corners": 200,
            "min_distance": 25,
            "trail_length": 12,
            "traj_height": 360,
            "header_height": 44,
            "path_topic": "/vins_estimator/path",
            "odom_topic": "/vins_estimator/odometry",
            "output_topic": "/vins/fisheye_track",
            "mask_path": str(Path(args.fisheye_mask).resolve()) if args.fisheye_mask else "",
        }

    # ------- optional launch file -------
    if args.launch:
        args.launch_dir.mkdir(parents=True, exist_ok=True)
        launch_path = emit_launch(args.launch_dir, args.launch, main_yaml,
                                  padder_specs=padder_specs,
                                  viz_spec=viz_spec)
        print(f"[ok ] wrote {launch_path}")

    # ------- summary -------
    print()
    print("Summary:")
    print(f"  cam pair   : cam{cam_pair[0]} + cam{cam_pair[1]}")
    print(f"  baseline   : {np.linalg.norm(Tic[cam_pair[0]][:3,3] - Tic[cam_pair[1]][:3,3]):.4f} m")
    print(f"  imu rate   : {imu0.get('update_rate','?')} Hz")
    print(f"  td (kalibr): {timeshift:+.6f} s  (image_t + td = imu_t)")
    print(f"  imu noise  : x{args.imu_noise_scale}")
    if pad_total > 0:
        w0, h0 = resolution
        print(f"  pad        : t={args.pad_top} b={args.pad_bottom} "
              f"l={args.pad_left} r={args.pad_right}  "
              f"->  {w0+args.pad_left+args.pad_right} x {h0+args.pad_top+args.pad_bottom}")
    print()
    print("Run:")
    print(f"  roslaunch vins {(args.launch or 'my_kalibr_fisheye')}.launch")
    print(f"  rosbag play <your.bag> --clock")


if __name__ == "__main__":
    main()
